project:
  type: website

website:
  title: "RENIGH Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: principales_indicadores_con_R_original.qmd
        text: Original
        
        
format:
  html:
    theme: 
      dark: cyborg
      light: superhero
    css: styles.css
    toc: true
    smooth-scroll: true

editor: visual

